### ISSUE TITLE
KeyError: 'backbone.backbone.dark2.1.m.1.conv1.bn'

### ISSUE THREAD

**Issue by ouening** [zongxin1993/YOLOX_pruning#5]
修改为s模型使用prune_train/prune.py训练后报错：
```
/usr/local/lib/python3.9/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
0.14189600944519043
8937682
Traceback (most recent call last):
  File "/media/disk4t/DeepLearningProjects/projects/20220123yolov5-attention/YOLOX_pruning/YOLOX/../prun_train/prune.py", line 316, in <module>
    main(exp,args)
  File "/media/disk4t/DeepLearningProjects/projects/20220123yolov5-attention/YOLOX_pruning/YOLOX/../prun_train/prune.py", line 281, in main
    pruned_model = init_weights_from_loose_model(
  File "/media/disk4t/DeepLearningProjects/projects/20220123yolov5-attention/YOLOX_pruning/YOLOX/../prun_train/prune.py", line 165, in init_weights_from_loose_model
    pruned_model = yolox_prun(mask_bn_channel_dict)
  File "/media/disk4t/DeepLearningProjects/projects/20220123yolov5-attention/YOLOX_pruning/prun_train/prune_model.py", line 627, in __init__
    backbone = YOLOPAFPN_prune(mask_bn_channel_dict=mask_bn_channel_dict)
  File "/media/disk4t/DeepLearningProjects/projects/20220123yolov5-attention/YOLOX_pruning/prun_train/prune_model.py", line 302, in __init__
    self.backbone = CSPDarknet_prune(
  File "/media/disk4t/DeepLearningProjects/projects/20220123yolov5-attention/YOLOX_pruning/prun_train/prune_model.py", line 119, in __init__
    bottle_cv1out = mask_bn_channel_dict[named_m_bottle_cv1_bn]
KeyError: 'backbone.backbone.dark2.1.m.1.conv1.bn'
```
请问怎么解决呢？

**Comment by zongxin1993** [comment]
> 修改为s模型使用prune_train/prune.py训练后报错：
> 
> ```
> /usr/local/lib/python3.9/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> 0.14189600944519043
> 8937682
> Traceback (most recent call last):
>   File "/media/disk4t/DeepLearningProjects/projects/20220123yolov5-attention/YOLOX_pruning/YOLOX/../prun_train/prune.py", line 316, in <module>
>     main(exp,args)
>   File "/media/disk4t/DeepLearningProjects/projects/20220123yolov5-attention/YOLOX_pruning/YOLOX/../prun_train/prune.py", line 281, in main
>     pruned_model = init_weights_from_loose_model(
>   File "/media/disk4t/DeepLearningProjects/projects/20220123yolov5-attention/YOLOX_pruning/YOLOX/../prun_train/prune.py", line 165, in init_weights_from_loose_model
>     pruned_model = yolox_prun(mask_bn_channel_dict)
>   File "/media/disk4t/DeepLearningProjects/projects/20220123yolov5-attention/YOLOX_pruning/prun_train/prune_model.py", line 627, in __init__
>     backbone = YOLOPAFPN_prune(mask_bn_channel_dict=mask_bn_channel_dict)
>   File "/media/disk4t/DeepLearningProjects/projects/20220123yolov5-attention/YOLOX_pruning/prun_train/prune_model.py", line 302, in __init__
>     self.backbone = CSPDarknet_prune(
>   File "/media/disk4t/DeepLearningProjects/projects/20220123yolov5-attention/YOLOX_pruning/prun_train/prune_model.py", line 119, in __init__
>     bottle_cv1out = mask_bn_channel_dict[named_m_bottle_cv1_bn]
> KeyError: 'backbone.backbone.dark2.1.m.1.conv1.bn'
> ```
> 
> 请问怎么解决呢？

我再代码中写死了是l 模型，你需要改一下模型深度和宽度系数

**Comment by ouening** [comment]
您好,模型我已经修改了s模型的深度和宽度了，稀疏训练还是正常的，就剪枝重训练这一步报错了

**Comment by ASDF623** [comment]
请问解决了嘛？

**Comment by ouening** [comment]
没有解决，已经换其他库了

**Comment by wumiaowang66** [comment]
> 没有解决，已经换其他库了

能麻烦问一下换的是哪个库吗

**Comment by lizexu123** [comment]
> 没有解决，已经换其他库了

请问是怎么解决的，能告诉一下吗大佬
